Sprint2/step2
TroyKiri/react-burger pull request #4
Opened 2021-06-25 08:25 UTC by TroyKiri

Здравствуйте!

Сделал следующее:

1. Обновил инфраструктуру приложения;
2. Подготовил хранилище, подключил Redux Devtools;
3. Описал экшены и редьюсеры
4. Доработал интерфейс навигации по ингредиентам;
5. Реализовал dnd

Спасибо за ревью!

2021-06-25 09:43 UTC, SmilingJey requested changes
Здравствуйте!

Неплохая работа работа. Стейт перенесен в redux, правильно работает добавление ингредиентов перетаскиванием

Но есть несколько замечаний:

**Замечания которые необходимо исправить:**

- разделите один большой редьюсер на небольший редьюсеры, каждый из которых решает небольшую задачу - загрузка данных ингредиентов, отправка заказа, конструктор. Так же разделите их в файловой системе - каждый редьюсер в своей папке

- сортировка элементов в конструторе работает некорректно. При перетаскивании элемента в конструкторе под ним должно отображатсья пустое пространство

- не нужно хранить отдельно в сторе ingredientsId массив id  для отправки, создавайте массив при отправке из данных конструктора. Иначе сейчас при отправке отправляются даже удаленные элементы. Вообще любое дублирование информации с сторе считается плохой практикой

- не работает удаление первого элемента в конструкторе

- вычисление цены перенесите в сам компонент, при выполнении редьюсера должен выполняться только код отвезающей задачи экшена. 

**Места, в которых можно улучшить проект:**

- из функций экшенов возвращайте промис

- счетчики ингредиентов можно считать в самом компоненте ,а не делать это в редьюсере


Подробнее замечания описаны ниже в комментариях к самим участкам кода:

2021-06-25 09:43 UTC, SmilingJey commented on src/services/actions/actions.js
> +    fetch(DATA_ID)
**Можно лучше**

здесь и в функции ниже лучше возврашать промис, это поможет обработать при необходимости этот промис при вызове dispatch и поможет так же при тестировании

```
export function getIngredients() {
  return function (dispatch) {
    dispatch({
      type: GET_INGREDIENTS_REQUEST,
    });

    return fetch(DATA_ID)
      ..............................
}
```

2021-06-25 09:43 UTC, SmilingJey commented on src/services/reducers/reducers.js
> +const initialState = {
**Надо исправить**

принято, что каждый редьюсер решает свою задачу, не стоит объединят ьвсе в одном редьюсере
Выделите редьюсер ингредиентов, конструктора и оформления заказа. В каждой папке будет редьюсер, экшены и селекторы относящиеся к этой доменной области, например как на скриншоте:
![Screenshot_37](https://user-images.githubusercontent.com/9317133/123399929-dd12fe00-d5ad-11eb-8a08-2095f56eccc7.png)

2021-06-25 09:43 UTC, SmilingJey commented on src/services/reducers/reducers.js
> +  const bunPrice = 2 * state.constructorIngredients.bun.price; // стоимость булочек
**Надо исправить**

здесь не должно быть вычисления цены, редьюсер должен выполнять только одно действие описанное в экшене.

Перенесите вычисление цены в сам компонент оберну вычесление в useMemo

```
const totalPrice= useMemo(() => {
   вычисление стоимости по выбранной булке и начинке
}, [bun, stuffing])
```

2021-06-25 09:43 UTC, SmilingJey commented on src/services/reducers/reducers.js
> +                count: countStuff,
**Можно лучше**

получить данные счетчика можно в самом компоненте
Примерно так:
```
const counters  = useMemo(() => {
     const counters = {};
     ingredients.forEach((ingredient) => {
      if (!counters[ingredient._id]) counters[ingredient._id] = 0;
      counters[ingredient._id]++;
    });
    if (bun) counters[bun._id] = 2;
    return counters;
}, [bun, ingredients])
```

где bun, ingredients - то, что добавлено в конструктор

2021-06-25 09:43 UTC, SmilingJey commented on src/services/reducers/reducers.js
> +    case DELETE_INGREDIENT_FROM_CONSTRUCTOR: {
**Надо исправить**

не работает удаление первого элемента в списке

2021-06-25 09:43 UTC, SmilingJey commented on src/services/reducers/reducers.js
> +    ingredientsId: [],
**Надо исправить**

не нужно хранить отдельно в сторе массив id для отправки. Их можно легко получить зная какие булки и какая начинака будут отправляться

А сейчас есть проблема - элементы не удаляются из ingredientsId при удалении из конструктора, в итоге отправляется запрос оформления заказа в котором есть даже ранее удаленные элементы

2021-06-25 09:43 UTC, SmilingJey commented on src/components/app/app.js
>      return () => document.removeEventListener('keydown', escHnalder);
**Можно лучше**

обработку закрытия по ESC лучше перенести в сам компонент модального окна

2021-06-25 09:43 UTC, SmilingJey commented on src/components/constructor-item/constructor-item.js
> +  const [{ handlerId }, drop] = useDrop({
**Надо исправить**

сортировка элементов в конструторе работает некорректно. При перетаскивании элемента в конструкторе под ним должно отображатсья пустое пространство

изучите как работает пример из документации https://react-dnd.github.io/react-dnd/examples/sortable/simple

2021-06-27 07:59 UTC, TroyKiri commented
### Здравствуйте!

Внес исправления:
1. Разделил редьюсер на небольшие редьюсеры:
- `ingredientsReducer`: загрузка ингредиентов;
- `constructorReducer`: функционал конструктора;
- `ingredientDetailsReducer`: отображение информации об ингредиенте;
- `orderReducer`: оформление заказа.
2. Реализовал корректную сортировку ингредиентов в конструкторе;
3. Реализовал создание массива с id ингредиентов в самом компоненте конструктора;
4. Пофиксил баг с отсутствием возможности удалить первый элемент в конструкторе;
5. Перенес в компонент вычисление цены и счётчик количества ингредиентов.
6. Реализовал возвращение промиса из функций экшенов

#### Спасибо за ревью!

2021-06-27 08:29 UTC, SmilingJey approved these changes
Вы отлично поработали над проектом, критические ошибки исправлены.

Но не забудьте обратить внимание не насколько оставленных замечаний, особенно на замечание по генерации id в редьюсере, т.к. в третьей проектной работе Вы столкнетесь с проблемами при тестировании редьюсера, если не исправить

Успехов в дальшейшем обучении

2021-06-27 08:29 UTC, SmilingJey commented on src/components/burger-constructor/burger-constructor.js
> +  const arrayOfStuffingId = stuffing.map((item) => item._id);
**Можно лучше**


перенесите вычисление массива id в функцию makeOrder, не нужно делать это при каждом рендере

2021-06-27 08:29 UTC, SmilingJey commented on src/components/burger-constructor/burger-constructor.js
> +  const priceOfStuffing = stuffing.reduce((prev, item) => {
**Модно лучше**

оберните вычисление стоимости в useMemo, что бы вычисления выполнялись тотлько когда необходимо

2021-06-27 08:29 UTC, SmilingJey commented on src/components/card-ingredient/card-ingredient.js
> +    stuffing.length && stuffing.filter((item) => item.name === props.item.name);
**Можно лучше**

филтровать нужно по id а не поимени

Лучше обернуть вычисление количества в useMemo, что бы оно производилось только при необходимости

2021-06-27 08:29 UTC, SmilingJey commented on src/services/reducers/constructorReducer.js
> +          stuffing: [...state.stuffing, { ...action.item, key: uuidv4() }],
**Надо исправить**

редьюсер должен быть чистой функцией, генерация id в редьюсере нарушает это правило, т.к. id каждый раз будет случайный. Генерируйте id при создании экшена и передавайте его вместе с payload в редьюсер

2021-07-11 15:22 UTC, merged